INSERT INTO Constellation(index, orgName, comment, planned, launched, firstLaunch, isFunded, fundingAmt) VALUES
	(1, 'ExactEarth', 'Own satellites called AprizeSat or ExactView. Now also hosted payloads on 58 Iridium-NEXT satellites.', 67, 57, 2008, True, NULL),
	(2, 'Planet', '29 MP sensor taking images with 3.7 m ground resolution and swath of 24.6 km  x 16.4 km from 475 km altitude.', 150, 324, 2013, True, 183000000),
	(3, 'Spire', 'Measure change in GPS signal after passing atmosphere to calculate precise profiles for temperature, pressure, humidity.', 150, 85, 2013, True, 149500000),
	(4, 'Planet (Terra Bella / Skybox)', 'Color and near-infrared imagery (90 cm resolution) in 120 kg package. First-ever commercial high-resolution video from a satellite.', 24, 13, 2013, NULL, NULL),
	(5, 'Astro Digital (Aquila)', '6U has 22 m resolution in RGB and NIR. 16U has 2.5 m resolution in RGB, red edge, and NIR using one 70 MP sensor.', 25, 5, 2014, True, 16700000),
	(6, 'BlackSky / Spaceflight', 'Subsidiary of Spaceflight Industries. Color imagery at a resolution of 1 meter.', 60, 1, 2016, True, 203500000),
	(7, 'GHGSat', 'Measure CO2 and methane in a FoV of ~12 km  x 12 km and resolution of <50 m. Sensors include 2D Wide-Angle Fabry-Perot imaging spectrometer with 15 kg satellite.', 20, 1, 2016, True, 20000000),
	(8, 'Satellogic', 'NuSat 37 kg satellites are capable of 1 m ground resolution imaging and video.', 25, 3, 2016, True, 29000000),
	(9, 'Space View', 'First commercial 560 kg Chinese high-resolution Earth imaging satellites called SuperView (GaoJing) with resolution of 0.5 m per pixel.', 16, 5, 2016, NULL, NULL),
	(10, 'Xingyun', 'Plans to be completed by 2025.', 156, 1, 2017, NULL, NULL),
	(11, 'Sky and Space Global', 'Plans to use inter-satellite links. Satellites outsourced from GomSpace.', 200, 3, 2017, True, 11500000),
	(12, 'GeoOptics', 'Satellites outsourced from Tyvak.', NULL, 5, 2017, True, 5150000),
	(13, 'Zhuhai Orbita Control', 'Constellation of different video and hyperspectral satellites.', 10, 7, 2017, True, NULL),
	(14, 'Canon', '8K low-light real-time video and streaming using laser terminal.', 100, 1, 2017, NULL, NULL),
	(15, 'Aireon', 'Hosted payload on Iridum-NEXT satellites for global air traffic surveillance.', 75, 65, 2017, True, 50000000),
	(16, 'Helios Wire', 'Uses 30 MHz of S-band spectrum to receive tiny data packages from billions of sensors. First payloads hosted on Astro Digital Corvus/Landmapper CubeSats.', 30, 1, 2017, True, 1000000),
	(17, 'Swarm Technologies', 'World''s smallest two-way communication satellites.', NULL, 4, 2018, NULL, NULL),
	(18, 'Kepler Communications', 'Monthly fee based on the data amount. Hope to achieve rates of 1-40 Mbps. Clyde Space will provide at least the first 2 sats.', 140, 1, 2018, True, 21000000),
	(19, 'ICEYE', '21 launch agreement with Vector Space Systems. 10 platform agreement with York Space Systems.', 18, 1, 2018, True, 53000000),
	(20, 'SpaceX', '400 kg satellites according to FCC filing. First technology demonstration missions planned to fly in 2017.', 4425, 2, 2018, True, 1600000000),
	(21, 'Orbital Sidekick', 'First sensor on ISS. Constellation coming in 2020.', NULL, 1, 2018, True, 4700000),
	(22, 'Analytical Space', 'In-orbit relays receiving radio and downlink to ground with laser communication enabling more data downlink from satellites.', NULL, 1, 2018, True, 4000000),
	(23, 'PlanetiQ', 'Based on GPS radio occultation. Will have microwave spectrometer & radiometer. Blue Canyon Tech builds satellites.', 18, 0, 2018, True, 5000000),
	(24, 'Hiber (Magnitude Space)', 'Send small packets of data (140 characters, accompanied by time?stamp, identifier and location).', 48, 0, 2018, True, 6200000),
	(25, 'Fleet Space', 'Selected Saber Astronautics as the operations provider. Launches planned to be started in 2017.', 100, 0, 2018, True, 3700000),
	(26, 'Astrocast (ELSE)', 'Demonstration mission in 2018. Targeting L-band. Inter-satellite links. NanoSpace propulsion.', 64, 0, 2018, True, 7100000),
	(27, 'Blink Astro', 'Blink Astro and NanoAvionics have signed an agreement to fly a tech demo payload to LEO in fall 2018.', NULL, 0, 2018, NULL, NULL),
	(28, 'AISTech', '2-way comms, thermal imaging to detect forest fires, aviation tracking (ADS-B). Satellites will be built by GomSpace.', 100, 0, 2018, True, 310000),
	(29, 'HawkEye360', 'Radio frequency (RF) mapping with 15 kg sats to help monitor transportation across air, land, sea and assist in emergencies. Built by GomSpace.', 30, 0, 2018, True, 26000000),
	(30, 'Axelspace', 'Weighs < 95 kg and captures images with a 2.5-meter resolution over a 57-kilometer area.', 50, 0, 2018, True, 16000000),
	(31, 'Capella Space', 'Resolutions from 1 m (1600 km2) to 30 m (27,000 km2). Every 3-6 hours globally and 45 min in equatorial regions, improving to every hour in 3-5 years.', 40, 0, 2018, True, 34000000),
	(32, 'OneWeb', 'Joint venture with Airbus to build the constellation of 125 kg satellites.', 648, 0, 2018, True, 1700000000),
	(33, 'Karten Space', 'Optical resolution is 3-5 m.', 14, 0, 2018, NULL, NULL),
	(34, 'UnSeenLabs', 'Satellites outsourced from GomSpace.', NULL, 0, 2018, NULL, NULL),
	(35, 'NSLComm (SkyFi)', 'Up to 1 Gbps anywhere in the world with a novel antenna.', 60, 0, 2018, True, 9250000),
	(36, 'Kaskilo / eightyLEO', '10 Gbps intersatellite laser communication links. Ka-band for ground communications.', 300, 0, 2018, NULL, NULL),
	(37, 'Orbital Micro Systems', 'Utilizes microwave technology to capture temperature and moisture measurements, refreshed and delivered every 15 minutes.', 40, 0, 2018, True, 650000),
	(38, 'Hera Systems', 'Capable of 1-meter resolution with 22-kilogram form factor.', 50, 0, 2019, True, 4200000),
	(39, 'Hongyan', 'Completion in 2023 in multiple phases to provide global broadband access, voice communications and other services.', 320, 0, 2018, NULL, NULL),
	(40, 'SRT Marine', 'Scanning technology will enable the detection of vessels without an identification transceiver. Clyde Space will build the spacecraft.', 6, 0, 2019, NULL, NULL),
	(41, 'Reaktor Space', 'Hyperspectral constellation for smart agriculture with 100''s of spectral bands and 20 m resolution.', 36, 0, 2018, NULL, NULL),
	(42, 'SatRevolution', 'Imaging the Earth in 4m resolution through the use of an innovative lens.', 66, 0, 2018, True, 800000),
	(43, 'Aerial & Maritime', 'Monitoring aircraft (ADS-B) and vessels (AIS) from 37°N to 37°S. GomSpace is shareholder and will develop satellites. Cooperation with Flightradar24.', NULL, 0, 2019, True, 12200000),
	(44, 'Rupercorp', '2U CubeSat to be launched in 2018 will be a precursor for the commercial constellation based on NanoAvionics M6P with green chemical propulsion system.', NULL, 0, 2019, NULL, NULL),
	(45, 'Harris', 'Immediate access to 3D wind data sets from Harris-owned HyperCubes. Utah State University provides the spacecraft.', 12, 0, 2019, NULL, NULL),
	(46, 'Earth-i', 'First constellation in the world able to provide full-colour video.', 15, 0, 2019, NULL, NULL),
	(47, 'Synspective', 'Developing 3kW power amplifiers to realize 1m ground resolution.', 30, 0, 2019, True, 13600000),
	(48, 'Space Systems Engineering', 'Advanced Earth Observation VNIR optical instrument payload.', NULL, 0, 2019, NULL, NULL),
	(49, 'Astrome', 'Indian space technology company to provide high speed broadband internet from space.', 150, 0, 2019, NULL, NULL),
	(50, 'Audacy Space', '3 relay satellites in Medium Earth Orbit (MEO) for continous communication with satellites.', 3, 0, 2019, True, 11100000),
	(51, 'Cloud Constellation', 'Space-based cloud storage. An array of equatorial low earth orbiting data center satellites. Much more secure and in some cases better-performing. 10-gigabit laser communications links between satellites.', NULL, 0, 2019, True, NULL),
	(52, 'Transcelestial', 'Space data network for terrestrial and satellite applications. Using lasers to transfer data at up to 1000x faster than currently available.', NULL, 0, 2019, True, 1800000),
	(53, 'Dauria / SatByul', 'Perseus-O multispectral constellation. Many similarities to Astro Digital.', 8, 0, 2019, NULL, NULL),
	(54, 'Kleos Space', 'Radio data collection spacecraft with our patented In-Space Manufacturing technology, a miniature machine that manufactures enormous composite booms used to deploy antenna.', 20, 0, 2019, NULL, NULL),
	(55, 'HyperSat', 'Imaging over 200 spectral bands (wavelengths of light) with a sub-10 meter ground sample distance.', 6, 0, 2020, True, 85000000),
	(56, 'LaserFleet', 'Provide reliable 1 Gbps communication rates to aircraft at altitude. Higher effective data rate at a lower cost than the best-in-class Ku/Ka/V.', NULL, 0, 2020, True, 2000000),
	(57, 'Kineis', 'Two-way communications and propulsion.', 20, 0, 2020, True, NULL),
	(58, 'XpressSAR', 'Small-area spotlight images with resolutions under 1 meter. Four satellites in two orbit planes with a 35° inclination.', 4, 0, 2020, NULL, NULL),
	(59, 'Orora Tech', 'New patent pending CubeSat framework with high-end imaging sensors to accurately measure both surface temperatures and cloud coverage.', 100, 0, 2021, NULL, NULL),
	(60, 'Methera', 'Working on low-cost terminal design thanks to Innovate UK funding.', 16, 0, 2021, True, NULL),
	(61, 'Trident Space (Magna Parva)', 'Breakthrough compact radar technology and onboard machine learning for automated feature extraction and predictive analytics. Innovative light weight reflector. 300 kg satellites.', 48, 0, 2021, True, 7000000),
	(62, 'VEOWARE', 'Lease satellite time to its customers, providing them with essential imagery capacity.', NULL, 0, 2021, NULL, NULL),
	(63, 'Scepter', 'Air pollution monitoring precise enough to reveal conditions for individual city blocks.', NULL, 0, NULL, NULL, NULL),
	(64, 'Astranis', 'Ssmall GEO satellite weighing 300 kg to provide up to 10 Gb/s of bandwidth.', NULL, 0, NULL, True, 18000000),
	(65, 'Umbra Lab', 'Software defined radar. Groundbreaking power aperture area and launch volume. Range resolution ?0.25m, azimuth resolution ?0.10m.', 12, 0, NULL, True, NULL),
	(66, 'EarthNow', 'Continuous real-time video of the Earth enhanced by machine intelligence.', 500, 0, NULL, True, NULL),
	(67, 'OQ Technology', 'World''s first universal plug & play IoT device that can provide connectivity leveraging Low-Earth-Orbit satellite infrastructure.', NULL, 0, NULL, NULL, NULL),
	(68, 'Tekever', 'Constellation will carry the same observation and telecom payloads as Infante, but with different payloads on different satellites.', 12, 0, NULL, NULL, NULL),
	(69, 'ArQit', 'Quantum Key Distribution shared in laser transmissions from a satellite. Qinetiq is contractor for spacecraft.', NULL, 0, NULL, NULL, NULL),
	(70, 'NorStar NorthStar', 'First commercial system to combine Hyperspectral and Infrared sensors to observe Earth', 40, 0, NULL, NULL, NULL),
	(71, 'Laser Light', 'Optical laser comm constellation in MEO as an Internet infrastructure service.', 12, 0, NULL, NULL, NULL),
	(72, 'Koolock', 'The most advanced feature set for weather and environmental monitoring.', NULL, 0, NULL, NULL, NULL),
	(73, 'Alba Orbital', 'First PocketQube constellation.', NULL, 0, NULL, NULL, NULL),
	(74, 'Galaktika', 'Pulsar IoT constellation for two-way exchange of data packets at a speed up to 500 bit/sec.', NULL, 0, NULL, NULL, NULL),
	(75, 'Ubiquitilink', 'Leverage nanosatellites in a unique manner to provide connectivity anywhere on the planet.', NULL, NULL, NULL, True, NULL),
	(76, 'Hypercubes', 'Track not only the chemical output of factories and farms, but also the movement of machines and equipment.', NULL, 0, NULL, NULL, NULL),
	(77, 'Efir', 'Russian constellation in 870 km orbit operational in 2025.', 288, 0, NULL, NULL, NULL),
	(78, 'B612 Foundation', 'Track smaller, fast-moving asteroids in the range of 140 m to 1 km wide. Built by York Space Systems.', NULL, 0, NULL, NULL, NULL),
	(79, 'Planetary Resources', 'Visible-NIR 40 channel hyperspectral imager with 10 m resolution. Midwave infrared imager (MWIR) in 3-5 ?m with 15 m resolution. Has been deprioritized for asteroid missions.', 10, 2, NULL, True, 50000000),
	(80, 'Outernet', 'Broadcast free data from space. Revenue from ads, premium content and hardware sales. Cancelled in 2017 due to lack of launch funding.', 200, 0, NULL, True, NULL),
	(81, 'Ursa Space Systems', 'In parallel developing own constellation to provide priority access, superior revisit frequency, improved resolution and direct downlink.', NULL, 0, NULL, NULL, NULL),
	(82, 'Earthcube', 'Might use Exotrail thrusters.', 10, 0, NULL, True, 4500000),
	(83, 'Terran Orbital (Tyvak)', 'Building a constellation of best-in-class nanosatellites that will form an unprecedented data infrastructure in space.', NULL, 0, NULL, True, NULL),
	(84, 'ISIS / Innovative Data Services', 'AIS payload tested on Triton-1 and network planned for a while, but no recent news. ADS-B, M2M and asset tracking also considered.', 16, 0, NULL, NULL, NULL),
	(85, 'Promethean Labs', 'Special imager for measuring greenhouse gas (GHG) emissions, monitoring of water and air quality, forestry and land.', NULL, 0, NULL, NULL, NULL),
	(86, 'BitSat (Dunvegan Space Systems)', 'Providing communications, data processing, storage and broadcasting capabilities in space. Cancelled when fundraising fell through.', 24, 0, NULL, NULL, NULL),
	(87, '4skies (NovaNano)', 'Was one of the first in the field, but was not able to raise funding.', NULL, 0, NULL, NULL, NULL);