INSERT INTO Organization(name) VALUES
	('ExactEarth'),
	('Planet'),
	('Spire'),
	('Planet (Terra Bella / Skybox)'),
	('Astro Digital (Aquila)'),
	('BlackSky / Spaceflight'),
	('GHGSat'),
	('Satellogic'),
	('Space View'),
	('Xingyun'),
	('Sky and Space Global'),
	('GeoOptics'),
	('Zhuhai Orbita Control'),
	('Canon'),
	('Aireon'),
	('Helios Wire'),
	('Swarm Technologies'),
	('Kepler Communications'),
	('ICEYE'),
	('SpaceX'),
	('Orbital Sidekick'),
	('Analytical Space'),
	('PlanetiQ'),
	('Hiber (Magnitude Space)'),
	('Fleet Space'),
	('Astrocast (ELSE)'),
	('Blink Astro'),
	('AISTech'),
	('HawkEye360'),
	('Axelspace'),
	('Capella Space'),
	('OneWeb'),
	('Karten Space'),
	('UnSeenLabs'),
	('NSLComm (SkyFi)'),
	('Kaskilo / eightyLEO'),
	('Orbital Micro Systems'),
	('Hera Systems'),
	('Hongyan'),
	('SRT Marine'),
	('Reaktor Space'),
	('SatRevolution'),
	('Aerial & Maritime'),
	('Rupercorp'),
	('Harris'),
	('Earth-i'),
	('Synspective'),
	('Space Systems Engineering'),
	('Astrome'),
	('Audacy Space'),
	('Cloud Constellation'),
	('Transcelestial'),
	('Dauria / SatByul'),
	('Kleos Space'),
	('HyperSat'),
	('LaserFleet'),
	('Kineis'),
	('XpressSAR'),
	('Orora Tech'),
	('Methera'),
	('Trident Space (Magna Parva)'),
	('VEOWARE'),
	('Scepter'),
	('Astranis'),
	('Umbra Lab'),
	('EarthNow'),
	('OQ Technology'),
	('Tekever'),
	('ArQit'),
	('NorStar NorthStar'),
	('Laser Light'),
	('Koolock'),
	('Alba Orbital'),
	('Galaktika'),
	('Ubiquitilink'),
	('Hypercubes'),
	('Efir'),
	('B612 Foundation'),
	('Planetary Resources'),
	('Outernet'),
	('Ursa Space Systems'),
	('Earthcube'),
	('Terran Orbital (Tyvak)'),
	('ISIS / Innovative Data Services'),
	('Promethean Labs'),
	('BitSat (Dunvegan Space Systems)'),
	('4skies (NovaNano)'),
	('Orbital ATK'),
	('CASIC / Exspace'),
	('Rocket Lab'),
	('JAXA'),
	('LandSpace'),
	('Virgin Galactic'),
	('Vector Space'),
	('Zero 2 Infinity'),
	('bspace'),
	('CloudIX (Nine)'),
	('Astra Space'),
	('CTA'),
	('One Space'),
	('i-Space'),
	('Aevum'),
	('Rocketcrafters'),
	('CONAE'),
	('Firefly'),
	('ISRO'),
	('RocketStar'),
	('SpaceOps'),
	('Equatorial Space Industries'),
	('Link Space'),
	('Cubecab'),
	('Nammo'),
	('Gilmour Space'),
	('Open Space'),
	('abl space systems'),
	('Relativity Space'),
	('Reaction Dynamics'),
	('bluShift Aerospace'),
	('Thor Launch Systems'),
	('UP Aerospace'),
	('PLD Space'),
	('Interstellar Technologies'),
	('Aphelion Orbitals'),
	('Avio'),
	('Masterra Space'),
	('Space One (Canon, IHI)'),
	('SpinLaunch'),
	('Orbital Access'),
	('Smallspark Space Systems'),
	('Independence-X'),
	('Roketsan'),
	('Bagaveev Corporation'),
	('Horizon Space Tech'),
	('Scorpius Space Launch'),
	('Tranquility Aerospace'),
	('MISHAAL Aerospace'),
	('SpaceLS'),
	('Celestia Aerospace'),
	('VALT Enterprises'),
	('Lin Industrial'),
	('Orbex Space'),
	('Fore Dynamics'),
	('Skyrora'),
	('LAUNCHER Space'),
	('Rocketplane Global'),
	('Odyne Space'),
	('Ripple Aerospace'),
	('Swedish Space Corporation'),
	('Generation Orbit'),
	('Exos Aerospace'),
	('Chinarocket'),
	('Heliaq'),
	('LEO Aerospace'),
	('Bellatrix Aerospace'),
	('Stofiel Aerospace'),
	('New Rocket Technologies'),
	('Dawn Aerospace'),
	('i-Space (Space Honor)'),
	('Agnikul'),
	('MT Aerospace'),
	('Pythom'),
	('Rose Galactic'),
	('Advanced Rockets Coporation'),
	('HyImpulse'),
	('Pangea Aerospace'),
	('Spacedarts'),
	('Frontier Astronautics'),
	('Wagner Industries'),
	('Interorbital Systems'),
	('Leaf Space'),
	('ARCA Space'),
	('Open Space Orbital'),
	('Swiss Space Systems'),
	('Boeing'),
	('Sierra Nevada Corp'),
	('Lockheed Martin'),
	('ULA (United Launch Alliance)'),
	('Reaction Engines');