INSERT INTO Field(name) VALUES
	('AIS'),
	('Earth observation'),
	('Weather'),
	('ADS-B'),
	('Emissions monitoring'),
	('Hyperspectral'),
	('Internet'),
	('IoT / M2M'),
	('SAR'),
	('Orbital data relay'),
	('Optical comms'),
	('IR imaging'),
	('RF spectrum monitoring'),
	('Data storage'),
	('Geolocation'),
	('QKD'),
	('Asteroid tracking');